format = """
[░▒▓](#7aa2f7)\
[  ](bg:#7aa2f7 fg:#1a1b26)\
[](bg:#7aa2f7 fg:#7aa2f7)\
$directory\
[](fg:#7aa2f7 bg:#24283b)\
$git_branch\
$git_status\
[](fg:#24283b bg:#1f2335)\
$nodejs\
$rust\
$golang\
$php\
$python\
$lua\
$docker_context\
[](fg:#1f2335 bg:#1a1b26)\
$time\
[ ](fg:#1a1b26)\
\n$character"""

[directory]
style = "fg:#c0caf5 bg:#7aa2f7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#24283b"
format = '[[ $symbol $branch ](fg:#7aa2f7 bg:#24283b)]($style)'

[git_status]
style = "bg:#24283b"
format = '[[($all_status$ahead_behind )](fg:#7aa2f7 bg:#24283b)]($style)'

[nodejs]
symbol = ""
style = "bg:#1f2335"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#1f2335)]($style)'

[rust]
symbol = ""
style = "bg:#1f2335"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#1f2335)]($style)'

[golang]
symbol = ""
style = "bg:#1f2335"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#1f2335)]($style)'

[php]
symbol = ""
style = "bg:#1f2335"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#1f2335)]($style)'

[python]
symbol = ""
style = "bg:#1f2335"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#1f2335)]($style)'

[lua]
symbol = ""
style = "bg:#1f2335"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#1f2335)]($style)'

[docker_context]
symbol = ""
style = "bg:#1f2335"
format = '[[ $symbol $context ](fg:#7aa2f7 bg:#1f2335)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1a1b26"
format = '[[  $time ](fg:#c0caf5 bg:#1a1b26)]($style)'
